title: Maranacook High School Student Website
description: Website to track the Maranacook High School Student Government, Honor Societies, Clubs, and Events
url: "https://sawyer-rooney.github.io"
baseurl: "/Maranacook-Highschool-Student-Website"
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: dark
plugins:
  - jekyll-include-cache
masthead_title: "Maranacook Student Website"
collections:
  galleries:
    output: false
