title: Maranacook High School Student Website
description: Website to track the Maranacook High School Student Government, Honor Societies, Clubs, and Events
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: dark
plugins:
  - jekyll-include-cache

navigation: main
